# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version. 
version: 2

# Personal info
name: Aniket Nagrale
title: Senior Product Manager
email: aniketn.iitkgp@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  aniketnagrale
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: aniketnagrale.in
linkedin_username: aniketnagrale
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Results-driven Product Manager with 5+ years of experience in product strategy, analytics, and user engagement. Skilled in designing data-driven features, optimizing user journeys, and implementing growth strategies that drive retention and revenue. Adept at leveraging A/B testing, customer insights, and machine learning to refine product offerings. Strong technical acumen in SQL, Python, and analytics tools, with hands-on experience in fraud detection and automation. Experienced in stakeholder management, agile execution, and cross-functional collaboration to deliver impactful products that align with business goals.

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: OneCard (FPL Tech. Pvt. Ltd)
        link: https://www.getonecard.app/
        # link_text: boringcompany.com
        sub_title: Product Propositions Manager
        caption: October 2023 - Present
        quote: >
          Driving growth through product strategies and user engagement initiatives.
        description: | # this will include new lines to allow paragraphs
          - Implemented an automated 30-day handholding journey for newly onboarded users, enhancing feature adoption.
          - Strategized targets for Spends, ENR & activation based on seasonality, budget, and dynamic exclusive campaigns.
          - Built an in-app feature promoting offline transactions using OneCard, achieving a repeat rate of 60% with 90,000 monthly transactions.

      - layout: left
        title: Rapido (Roppen Transportation)
        link: https://www.rapido.bike/
        sub_title: Senior Product Manager
        caption: November 2020 - April 2023
        quote: >
          Enhancing ride experience and platform efficiency through data-driven solutions.
        description: |
         - Increased customer patience from 15.5s to 25.3s, improving Captain-to-Customer matching.
         - Improved Captain experience related to wallet transactions, reducing support calls by 22.5%.
         - Launched "Hotspots," increasing fulfillment by 25% and reducing pickup time by 17%.
         - Implemented a cancellation rate card system, improving fairness in cancellation charges and payouts.

      - layout: left
        title: Quantiphi Analytics Solution Pvt. Ltd.
        link: https://www.quantiphi.com/
        sub_title: Product Analyst
        caption: June 2019 - March 2020
        quote: >
          Driving agile product development and business intelligence solutions.
        description: |
         - Led sprint planning, PRD creation, and requirement gathering to align with release goals.
         - Collaborated with cross-functional teams for inter-team dependencies and business impact assessment.
         - Implemented Agile methodology for a team of 9, fostering a feedback-driven development culture.


      - layout: left
        title: Fractal Analytics Pvt. Ltd.
        link: https://fractal.ai/
        sub_title: Machine Learning Intern
        caption: May 2018 – Jul 2018
        quote: >
          Applied machine learning to forecast business KPIs and automate classification at scale.
        description: |
          - Built time-series models (ARIMA, FBProphet) for KPI forecasting, saving INR 1,20,000 in resourcing.
          - Used Spacy’s NER for entity tagging, eliminating manual effort in company/country/region classification.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Indian Institute of Technology, Kharagpur
        caption: 2015 - 2019
        sub_title: Bachelors of Technology
        quote: >
         "IIT Kharagpur taught me to think big, build fast, and always be curious."
        description: |
         - Developed a strong technical foundation through a rigorous curriculum.
         - Participated in Excellence Quotient by EXL for a customer prediction model.
         - Won Bronze in Hardware Modelling and Silver in Product Design competition.
         - Represented hostel in Inter-Hall Cricket (Silver) and Athletics (Bronze).
         - Learned teamwork, problem-solving, and managing complex deadlines.
         - Built adaptability and leadership by working with diverse teams.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Product Management and Analytics, some of my other interests and hobbies are:
      - Gym and Boxing
      - Gaming
      - Reading

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
